---
Name: knowledgebase
After: 'faq/*'
---

FAQSearchIndex:
  options:
    extraspath: '../knowledgebase/conf/extras'
    templatespath: '../knowledgebase/conf/templates'
  copy_fields:
    - _text
    - _spellcheckText